title = "Free Software Lab at NOI Techpark"
baseURL = "https://software.bz.it/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  #[[menu.header]]
  #  weight = 2
  #  name = "Work"
  #  url = "/work"
  #[[menu.header]]
  #  weight = 2
  #  name = "Digital Stations"
  #  url = "/stations"
  #[[menu.header]]
  #  weight = 3
  #  name = "Blog"
  #  url = "/blog"
  [[menu.header]]
    weight = 3
    name = "Services"
    url = "/service"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "NOI Techpark"
    url = "https://noi.bz.it"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "/contact"
  #[[menu.footer]]
  #  weight = 3
  #  name = "How it works"
  #  url = "#"
  #[[menu.footer]]
  #  weight = 4
  #  name = "Blog"
  #  url = "#"
  #[[menu.footer]]
  #  weight = 5
  #  name = "Terms"
  #  url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "FREE SOFTWARE LAB <br/> at NOI Techpark"
    subtitle = "A place to meet and discover innovative tecnologies"

  [params.wrapper]
    enable = true
    title = "Free Software Lab"
    #italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
    paragraph = "The Free Software Lab is a meeting point between research institutions and companies involved in Research & Development projects in the digital field. The laboratory is therefore an open platform for the development and support of R&D projects related to information technology. The Free Software Lab deploys the experience of a network of experts to provide services close to the needs of local companies."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Services"
    content = "Free Software Lab provides different services to support your R&D activities. Take a look at our service catalog."
    [params.feature.button]
      caption = "Explore Services"
      url = "/service"

  [params.call]
    enable = false
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = false
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work,"
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Our contacts"
      address = "NOI Techpark - Via Volta 13A, Bolzano/Bozen - Italy"
      email = "Email: info@software.bz.it"
      phone = "Phone: +39 0471 096 675"
    [params.contact.gmaps]
      title = "How to reach us"
