title = "Free Software Lab at NOI Techpark"
baseURL = "https://software.bz.it/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  #[[menu.header]]
  #  weight = 2
  #  name = "Work"
  #  url = "/work"
  #[[menu.header]]
  #  weight = 2
  #  name = "Digital Stations"
  #  url = "/stations"
  [[menu.header]]
    weight = 3
    name = "Our Services"
    url = "/service"
  [[menu.header]]
    weight = 4
    name = "Collaborate with us"
    url = "/collaborate"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "NOI Techpark"
    url = "https://noi.bz.it"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "/contact"
  #[[menu.footer]]
  #  weight = 3
  #  name = "How it works"
  #  url = "#"
  #[[menu.footer]]
  #  weight = 4
  #  name = "Blog"
  #  url = "#"
  #[[menu.footer]]
  #  weight = 5
  #  name = "Terms"
  #  url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "FREE SOFTWARE LAB <br/> at NOI Techpark"
    subtitle = "A place to meet and discover innovative tecnologies"

  [params.wrapper]
    enable = true
    title = "Free Software Lab"
    #italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
    paragraph = "Software development teams often need a test environment to consider investment in new software development trends. The Free Software Lab offers a technically equipped room and expert support to develop software prototypes with a variety of new technologies (LoRaWAN, Beacon, 5G, ...) and instruments (Speech Assistants, ...). Software development teams can learn about new software development processes and technologies in the Free Software Lab to prepare for R&D projects."
    image = "img/wrapper-img.png"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Services"
    content = "Free Software Lab provides different services to support your R&D activities. Take a look at our service catalog."
    [params.feature.button]
      caption = "Explore Services"
      url = "/service"
    [params.feature.button2]
      caption = "Collaborate with us"
      url = "/collaborate"

  [params.call]
    enable = false
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = false
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Our contacts"
      address = "NOI Techpark - Via Volta 13A, Bolzano/Bozen - Italy"
      email = "Email: info@software.bz.it"
      phone = "Phone: +39 0471 096 675"
    [params.contact.gmaps]
      title = "How to reach us"
