version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ../docker/dockerfile-node
      target: dev
    restart: unless-stopped
    command: npm start
    ports:
      - "1009:3000"
